### ISSUE TITLE
VerifyInclusion over the subtree roots

### ISSUE THREAD

**Issue by vgonkivs** [celestiaorg/nmt#178]
Currently, the node team is implementing a Blob Module that requires proof verification. We have`Included` method that ensures that the requested blob was included in the DAH at a certain height. As our light nodes do not store leaves, it
will be very complicated for them because they will have to request all leaves from other nodes and verify the inclusion.
In fact, `verifyInclusion` reconstructs the Merkle tree root from leaves and `Nodes` and compares it with the passed one.
It will be very helpful for us if we could verify the inclusion using subtree roots(built from leaves). These subtree roots will be constructed on 1 level above the leaves.

```ascii
                a
              /   \
            /       \
          /           \
        b              c
      /   \         /     \
    d      e       f       g
  /  \    /  \   /   \   /   \
[S1][S2][S3][S4][S5][S6][S7][S8]
```   

For example, we want to reconstruct the tree using `f` and `g` subtree roots(b will be stored in `Nodes` in the nmt.Proof)

**Comment by Wondertan** [comment]
+1, for now, we went with the approach that fetches all the leaves to optimize later. Once the [Blob module lands](https://github.com/celestiaorg/celestia-node/pull/2052), it will become blocking.

**Comment by vgonkivs** [comment]
Yes, so `VerifyInclusion(1)` will reconstruct the Merkle Root from f and g subtree roots(and not  from S5,S6,S7,S8 leaves)

**Comment by vgonkivs** [comment]
Meant that this is the second implementation of VerifyInclusion. Sorry for the confusion 😅

**Comment by rootulp** [comment]
I have a clarifying question. I interpret the diagram for an NMT like so:

```ascii
                a
              /   \
            /       \
          /           \
        b              c
      /   \         /     \
    d      e       f       g
  /  \    /  \   /   \   /   \
  h   i   j  k   l   m   n   o
  |   |   |  |   |   |   |   |
[S1][S2][S3][S4][S5][S6][S7][S8]
```

where `S1` is share 1 and `h` is the namespaced hash of S1 (see [HashNode](https://github.com/celestiaorg/nmt/blob/eb012d08857e799fcb0ac7af39d17caa7ece97e1/hasher.go#L230-L246)). Given such a diagram, does this proposal describe using the namespaced hash for each share (i.e. `h` through `o`) rather than `f` - `g`?

**Comment by vgonkivs** [comment]
Sounds good to me

**Comment by vgonkivs** [comment]
why?

**Comment by Wondertan** [comment]
>  suggested a better approach

From our private discussion, I had an impression that the approach is already implemented.  But if not, then nvm

**Comment by vgonkivs** [comment]
> the approach is already implemented

No, I meant it will be easier to implement it than my

**Comment by staheri14** [comment]
If what is described in this [proposal](https://github.com/celestiaorg/nmt/issues/178#issuecomment-1513655569) is sufficient for your use-case, then we already have a private method [verifyLeafHashes](https://github.com/celestiaorg/nmt/blob/master/proof.go#L231) in the nmt lib that can take the hash of leaves, instead of the leaves, and can verify their inclusion, however, there is a constraint and that is all the leaf hashes should belong to the same namespace ID.

**Comment by vgonkivs** [comment]
@staheri14, all leaf hashes will belong to the same nID.

> We just need to make that method public.

yeah, I had the same thoughts.
